### ISSUE TITLE
Support headers as proplists

### ISSUE THREAD

**Issue by davoclavo** [inaka/shotgun#125]
Currently shotgun expects headers as a map: `#{binary => binary}`, I guess it should also support proplists `[{binary, charlist}]` pairs, as it is the way gun expects headers: https://github.com/ninenines/gun/blob/master/doc/src/guide/http.asciidoc#get-and-head

**Comment by jfacorro** [comment]
Closed by #113

**Comment by davoclavo** [comment]
Awesome! Just for reference, I think you meant #133

**Comment by jfacorro** [comment]
@davecaos yeah, that what I meant, Just fixed it.
