### ISSUE TITLE
call to undefined function shotgun:wait_response/3

### ISSUE THREAD

**Issue by dzimi** [inaka/shotgun#134]
Hi,

my code triggered a crash report caused by shotgun process after I've used a wrong server port to open the connection. The code is as fallows:

    {ok, Conn} = shotgun:open(Host, Port),

    %first request which returned timeout
    {error,{timeout,{gen_fsm,sync_send_event,[<0.426.0>,{post,_Req},5000]}}} = shotgun:post(Conn,Url, Hrs, Body, #{timeout => 5000}),

    %try to run second request on the same connection
    Resp2 = shotgun:post(Conn, Url, Hrs, Body, #{timeout => 5000}),

    %GOT ERROR:
    gen_fsm <0.426.0> in state wait_response terminated with reason: call to undefined function shotgun:wait_response/3 from gen_fsm:handle_msg/7 line 503

    Resp2 = {error,{{undef,[{shotgun,wait_response,[{post,_}},5000]}}}

     [error] [custom] CRASH REPORT Process <0.426.0> with 0 neighbours exited with reason: call to undefined function shotgun:wait_response({post,{"/123",[{<<"Content-Type">>,<<"text/xml;charset=UTF-8">>},{<<"SOAPAction">>,<<"http://www.h...">>}],...}}, {<0.380.0>,#Ref<0.0.0.906>}, #{async => false,async_mode => binary,buffer => <<>>,data => <<>>,from => {<0.380.0>,#Ref<0.0.0.869>},...}) in gen_fsm:terminate/7 line 611

I've changed my code no to run the second request, but I think that this case should be handled. 
Thanks for feedback.

**Comment by jfacorro** [comment]
@dzimi Thanks for contributing! This same issue has been reported and fixed in #96 but we haven't created a release that includes the fix yet. We will do so in the near future, in the meantime you might want to use the latest commit to the master branch. Please let us know if you have any other issues.
