### ISSUE TITLE
Test non SSE chunked streams

### ISSUE THREAD

**Issue by unbalancedparentheses** [inaka/shotgun#15]

**Comment by kennethlakin** [comment]
The following works for me, in what's currently latest master:

Compile and run https://github.com/ninenines/cowboy/tree/master/examples/chunked_hello_world (Except that I changed the listen port to 8081)

Verify in curl that the data is sent incrementally (I got one line transferred per second):
```
$ curl http://localhost:8081
Hello
World
Chunked!
$
```

Then, do this in a shell with shotgun loaded, and observe the following results:
```
1> application:ensure_all_started(shotgun).
{ok,[ranch,cowlib,asn1,public_key,ssl,gun,shotgun]
2> {ok, Pid} = shotgun:open("localhost", 8081).
{ok,<0.77.0>}
3> shotgun:get(Pid, "/").
{ok,#{body => <<"Hello\r\nWorld\r\nChunked!\r\n">>,
      headers => [{<<"transfer-encoding">>,<<"chunked">>},
       {<<"connection">>,<<"keep-alive">>},
       {<<"server">>,<<"Cowboy">>},
       {<<"date">>,<<"Tue, 10 Nov 2015 03:44:55 GMT">>}],
      status_code => 200}}
4> 
```

So, is this bug closed, or did I totally misunderstand what tests were required?

**Comment by elbrujohalcon** [comment]
Thanks @kennethlakin :)
