### ISSUE TITLE
switch from deprecated gen_fsm to gen_statem

### ISSUE THREAD

**Issue by crvarner** [inaka/shotgun#178]
Not sure what the project's OTP support commitment is (I've seen other projects claim to only support the 3 most recent OTP releases), but OTP 21 complains about deprecated gen_fsm during compilation.

**Comment by elbrujohalcon** [comment]
Good point. We generally support only the latest OTP release in `master`. You can always use older versions of `shotgun` with older versions of OTP.
With that in mind, we should consider this a bug and fix it by replacing `gen_fsm` by `gen_statem` as you correctly point out.
