### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hez** [inaka/shotgun#179]
Looks like the last release of shotgun was quite a while ago, 2016, and there have been quite a few changes since: https://github.com/inaka/shotgun/compare/0.3.0...master

**Comment by jfacorro** [comment]
New release just create [0.4.0](https://github.com/inaka/shotgun/releases/tag/0.4.0)! 😄

Sorry it took so long!

**Comment by hez** [comment]
This is fantastic! Thank you for the great work!

**Comment by unix1** [comment]
Thank you for the new tag. Would it be possible to also publish it on hex.pm as with previous releases?

**Comment by elbrujohalcon** [comment]
[Done](https://hex.pm/packages/shotgun/0.4.0).
