### ISSUE TITLE
Any plan for Gun v2?

### ISSUE THREAD

**Issue by phunehehe** [inaka/shotgun#193]
Hi!

I happened to hack up some support for `shotgun` in a project that needs `gun` v2 (the [timeline](https://github.com/ninenines/gun/issues/268) for release is unclear but the RC has been out for a while now). The only problem that I see is `transport_opts` has been split into `tcp_opts` and `tls_opts`. With the following patch it works fine for my use: https://github.com/inaka/shotgun/compare/master...phunehehe:shotgun:gun2.

I figure it might be too early to actually incorporate changes like this into `shotgun`, but just in case there is interest in a `gun2` branch, I hope it helps.

Thanks,
Phu

**Comment by elbrujohalcon** [comment]
Hi @phunehehe. Thanks for the contribution. We're not actively maintaining or using this project that much lately. So, if others like you would like to use `gun2`'s RC, I'm fine with merging a PR with those changes.

**Comment by phunehehe** [comment]
Hi again @elbrujohalcon!
It turned out Gun 2.0.0 has been released, so I have updated the PR to use that instead of the RC.

**Comment by elbrujohalcon** [comment]
You're now an official maintainer, @phunehehe … Feel free to create a new release of the project if you need to :)
