### ISSUE TITLE
shotgun fails to compile on 0.1.6 and fbe44e2 using R16B03

### ISSUE THREAD

**Issue by ctradu** [inaka/shotgun#60]
Steps:
git clone https://github.com/inaka/shotgun
cd shotgun
make

Result using erlang R16B03:
...
./rebar compile
==> sync (compile)
Compiled src/sync_options.erl
Compiled src/sync_utils.erl
Compiled src/sync_scanner.erl
Compiled src/sync.erl
Compiled src/sync_notify.erl
make[1]: Leaving directory `/root/git/sipxecs/custom/reach-app/deps/shotgun/deps/sync'
 ERLC   shotgun_app.erl shotgun.erl shotgun_sup.erl
src/shotgun.erl:59: syntax error before: '{'
src/shotgun.erl:65: syntax error before: '{'
src/shotgun.erl:67: syntax error before: '{'
src/shotgun.erl:120: syntax error before: '{'
src/shotgun.erl:125: syntax error before: '{'
src/shotgun.erl:201: syntax error before: '{'
src/shotgun.erl:242: syntax error before: '{'
src/shotgun.erl:271: syntax error before: '{'
src/shotgun.erl:284: syntax error before: '{'
src/shotgun.erl:301: syntax error before: '{'
src/shotgun.erl:311: syntax error before: '{'
src/shotgun.erl:338: syntax error before: '{'
src/shotgun.erl:380: syntax error before: '{'
src/shotgun.erl:419: syntax error before: '{'
src/shotgun.erl:451: syntax error before: '{'
src/shotgun.erl:492: syntax error before: '{'
src/shotgun.erl:519: syntax error before: '{'
src/shotgun.erl:12: function get/2 undefined
src/shotgun.erl:12: function get/3 undefined
src/shotgun.erl:12: function request/6 undefined
src/shotgun.erl:41: function handle_sync_event/4 undefined
src/shotgun.erl:41: function init/1 undefined
src/shotgun.erl:41: function terminate/3 undefined
src/shotgun.erl:50: function at_rest/3 undefined
src/shotgun.erl:50: function parse_event/1 undefined
src/shotgun.erl:50: function receive_data/2 undefined
src/shotgun.erl:50: function wait_response/2 undefined
src/shotgun.erl:64: type response() undefined
src/shotgun.erl:118: spec for undefined function shotgun:get/2
src/shotgun.erl:123: spec for undefined function shotgun:get/3
src/shotgun.erl:155: function request/6 undefined
src/shotgun.erl:161: function request/6 undefined
src/shotgun.erl:167: function request/6 undefined
src/shotgun.erl:173: function request/6 undefined
src/shotgun.erl:179: function request/6 undefined
src/shotgun.erl:185: function request/6 undefined
src/shotgun.erl:191: function request/6 undefined
src/shotgun.erl:196: spec for undefined function shotgun:request/6
src/shotgun.erl:196: type headers() undefined
src/shotgun.erl:196: type options() undefined
src/shotgun.erl:238: spec for undefined function shotgun:parse_event/1
src/shotgun.erl:259: spec for undefined function shotgun:init/1
src/shotgun.erl:279: spec for undefined function shotgun:handle_sync_event/4
src/shotgun.erl:300: spec for undefined function shotgun:terminate/3
src/shotgun.erl:310: spec for undefined function shotgun:at_rest/3
src/shotgun.erl:334: spec for undefined function shotgun:wait_response/2
src/shotgun.erl:376: spec for undefined function shotgun:receive_data/2
src/shotgun.erl:403: function manage_chunk/4 undefined
src/shotgun.erl:434: function maps_get/3 is unused
src/shotgun.erl:444: function do_http_verb/3 is unused
src/shotgun.erl:500: function basic_auth_header/1 is unused
src/shotgun.erl:513: function encode_basic_auth/2 is unused
src/shotgun.erl:534: function check_uri/1 is unused
make: *** [ebin/shotgun.app] Error 1

**Comment by igaray** [comment]
Hi @ctradu as you probably figured out already, shotgun uses maps, which means it requires at least Erlang 17. We have added this to the README.md to make it more explicit.

**Comment by ctradu** [comment]
Well, if this library provides support only for Erlang 17 or newer, it is useless for older releases.
In some production environments R16 may be very well used for a number or years.
In conclusion, thank you for adding the mention in README.md
