### ISSUE TITLE
Shotgun supervisor does not realize children die

### ISSUE THREAD

**Issue by igaray** [inaka/shotgun#70]
Running tests which use shotgun usually leave the following messages in the logs: 

```
16:33:23.060 [error] <0.272.0> [::] Supervisor shotgun_sup had child shotgun started with shotgun:start_link() at undefined exit with reason noproc in context shutdown_error
```

When closing the gun process, if you call `is_alive` on its `pid` it will report `false`, asking for the process info will return `undefined`, but calling `supervisor:which_children(shotgun_sup)` the `pid` will be included in the children's list.

**Comment by jfacorro** [comment]
@igaray I think this might be related to this issue ninenines/gun#39.

**Comment by jfacorro** [comment]
I think I found the problem.

`shotgun` FSMs are started as children under `shotgun_sup` [here](https://github.com/inaka/shotgun/blob/master/src/shotgun.erl#L278), but the way the children is being killed when `shotgun:close/1` is called is by returning `{stop, normal, StateData}` in the `handle_event/3` callback. The supervisor then just restarts the child and the connection never really dies. 

So we are actually **never** removing the connection, just replacing it for a new one that will never be used :disappointed:.

**Comment by jfacorro** [comment]
#92
