### ISSUE TITLE
Update gun version to 1.0.0-pre.1

### ISSUE THREAD

**Issue by jfacorro** [inaka/shotgun#73]
ninenines/gun#69

**Comment by essen** [comment]
Actually make that 427230d6f94f5b8a396fd504a73d73d1d65ab0a7 (the commit right after) otherwise you fetch a version that breaks current erlang.mk. Thanks!

**Comment by essen** [comment]
It should be a straightforward update by the way, little has changed, there's just a couple bug fixes and many SPDY tests added (some of them still failing because I only added the tests, not their fixes).

**Comment by jfacorro** [comment]
@essen Awesome. Thanks for the information, will update to `427230d6f94f5b8a396fd504a73d73d1d65ab0a7`.
